README.md, spec/API/QueryFieldServiceSpec.php, src/API/QueryFieldService.php, src/FieldType/Query/Type.php
Adds two variables to the expression language used for parameters:
- `string returnedType`: identifier of the content type selected in the field definition
- `Location mainLocation`: main location of the field's content item
=> New expressions variables: mainLocation and returnedType

src/Symfony/Resources/config/services/ezplatform.yml
The alias used to match query fields definitions was not public, making it unusable as it gets loaded through the container.
Test by configuring a custom view for a query field:
```
ezpublish:
system:
default:
content_view:
content_query_field:
gallery_images:
match:
Identifier\ContentType: gallery
Identifier\FieldDefinition: images
template: "content/view/content_query_field/gallery_images.html.twig"
```
=> Fix EZP-31288: made the Identifier\FieldDefinition alias public

spec/API/QueryFieldServiceSpec.php, src/Controller/QueryFieldRestController.php
> [EZP-31276](https://jira.ez.no/browse/EZP-31276)
Updates the namespaces used for REST value objects in the REST controllers to matche the `ezsystems/ezplatform-rest` package.
=> Fixed REST value objects namespaces

src/Symfony/DependencyInjection/Compiler/FieldDefinitionIdentifierViewMatcherPass.php, src/Symfony/EzSystemsEzPlatformQueryFieldTypeBundle.php, src/Symfony/Resources/config/services/ezplatform.yaml
> [EZP-31288](https://jira.ez.no/browse/EZP-31288)
The short Field Definition Identifier matcher (`Identifier\FieldDefinition`) can not be supported in the current state of the 8.0 kernel (see https://github.com/ezsystems/ezpublish-kernel/pull/2916 for details and discussion). As it is what is documented, and because it is more convenient, it needs to be supported in the current beta.
The plan is to remove it once we have matchers with proper string literal identifiers.
I have also tried using decorators on various elements of the view matcher layer, but it is not suited for that unfortunately.
This pull-requests processes the semantic config using a compiler pass to replace the short identifier with the full service ID.
=> Workaround for EZP-31288 (FieldDefinition Identifier matcher)

composer.json, doc/howto/customize_rendering.md, spec/GraphQL/ContentQueryFieldDefinitionMapperSpec.php, src/API/QueryFieldPaginationService.php, src/API/QueryFieldService.php, src/Controller/QueryFieldRestController.php, src/GraphQL/ContentQueryFieldDefinitionMapper.php, src/GraphQL/QueryFieldResolver.php, src/Symfony/Resources/config/services/graphql.yml, src/Symfony/Resources/views/content/contentquery.html.twig, src/Symfony/Resources/views/fieldtype/field_view.html.twig, src/Symfony/Resources/views/fieldtype/fielddefinition_edit.html.twig, src/eZ/ContentView/QueryResultsInjector.php, src/eZ/ContentView/QueryResultsPagerFantaAdapter.php, src/eZ/FieldType/Mapper/QueryFormMapper.php, src/eZ/FieldType/Query/Type.php, src/eZ/Persistence/Legacy/Content/FieldValue/Converter/QueryConverter.php
> [EZP-31316](https://jira.ez.no/browse/EZP-31316)
Adds pagination support to the query field (1.0, eZ Platform 2.5).
Two new settings are added to the field type:
- a boolean, `EnablePagination`
- an integer, `ItemsPerPage`
The `QueryFieldService` is extended with a `QueryFieldPaginationService`, with two new methods:
- `loadContentItemsSlice(Content $content, string $fieldDefinitionIdentifier, int $offset, int $limit)`: loads a slice of the results
- `getPaginationConfiguration(Content $content, string $fieldDefinitionIdentifier)`: returns either 0 if pagination is disabled, or the default page size
When pagination is enabled for a field, the `QueryResultsInjector` (that adds the Query Field's results to the content view) will set `items` to a `PagerFanta` instance with a …
=> Pagination support (1.0)

src/GraphQL/QueryFieldResolver.php, src/eZ/ContentView/QueryResultsInjector.php
> Fixes [EZP-31364](https://jira.ez.no/browse/EZP-31364)
Removes checks on the deprecated interface `QueryFieldPaginationService`. They were failing because the `QueryFieldService` doesn't implement it in 2.0. They should have been removed when merging from 1.0 anyway.
=> Fix EZP-31364: removed checks on deprecated QueryFieldPaginationService

src/API/QueryFieldService.php
> Fixes [EZP-31365](https://jira.ez.no/browse/EZP-31365)
When the results from a query field are requested, but the content doesn't have such a field, a 500 error occurs. With this fix, a proper 404 explaining the issue is returned.
```json
{
"ErrorMessage": {
"_media-type": "application/vnd.ez.api.ErrorMessage+json",
"errorCode": 404,
"errorMessage": "Not Found",
"errorDescription": "Could not find 'Query field definition' with identifier 'folder/images'",
}
}
```
To test, call the query field REST source with the ID of a content that does not have the requested query field definition identifier:
```
https://example.com/api/ezp/v2/content/objects/1/versions/9/fields/images/query/results
```
=> Fix EZP-31364: throw a 404 if requested field doesn't exist

src/eZ/ContentView/QueryResultsInjector.php
> Fixes [EZP-31364](https://jira.ez.no/browse/EZP-31364)
An exception constructor had the wrong number of arguments because of a missing `sprintf()`. Fixed for 2.0 in https://github.com/ezsystems/ezplatform-query-fieldtype/pull/23.
=> Fixed EZP-31364: wrong exception ctor call

.travis.yml
This PR changes Travis setup a bit. Things done:
1) Simpliefied test matrix. Currently the result is 4 jobs: https://travis-ci.com/ezsystems/ezplatform-query-fieldtype/builds/148219759 and I think running codestyle twice (on different PHP versions) is not intended. Now there are 3 jobs.
2) Added Slack notifications, so we can detect failures earlier.
3) Disabled xdebug for performance
Background:
- we've written a simple browser tests that makes sure that Content Query can be used in AdminUI and I want to include it in the tests matrix in master, but first I'd like to add notifications. So you can expect another PR to master soon 😉
=> [Travis] Added notifications and listed jobs explicitly

composer.json, spec/API/QueryFieldServiceSpec.php
| **JIRA issue**                          | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0.0`
This PR replaces `ezpublish-kernel` with `ezplatform-kernel` and fixes dependency issues blocking package installation (due to Composer minimum stability requirements):
- `ezsystems/doctrine-dbal-schema:^1.0@dev` is required  by `ezplatform-kernel:^1.0@dev`
- other packages are required by `ezsystems/ezplatform-admin-ui:^2.0@dev`
=> EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel

src/Symfony/Resources/views/content/contentquery.html.twig
> Fixes [EZP-31514](https://jira.ez.no/browse/EZP-31514)
Instead of using the `location` object as the argument for the pager, it uses `_ez_content_view` with the `contentId` and `locationId` arguments.
The documentation needs to be updated for customizing the pager.
=> Fix EZP-31514: use _ez_content_view route for pagerfanta

.php_cs.spec, .travis.yml, composer.json, spec/API/QueryFieldServiceSpec.php, spec/GraphQL/ContentQueryFieldDefinitionMapperSpec.php, spec/GraphQL/QueryFieldResolverSpec.php, spec/eZ/ContentView/QueryResultsInjectorSpec.php, spec/eZ/Persistence/Legacy/Content/FieldValue/Converter/QueryConverterSpec.php
|  |  |
| --- | --- |
| **Target branch** | 1.0 for eZ Platform 2.5 LTS CI CS setup |
| **Failing build** | [Travis job 349271347](https://travis-ci.com/github/ezsystems/ezplatform-query-fieldtype/jobs/349271347#L462-L466)
Looks like we're one rule apart from applying some automation to CS checks for `spec` directory containing Spec tests. It's important that we automate those checks.
The difference in Spec tests, compared to production code is lack of `public` in testing method signature. The reason for that is that those method signatures are already long.
Applying rules for specific paths is not possible (see feature requests: FriendsOfPHP/PHP-CS-Fixer#3126 and FriendsOfPHP/PHP-CS-Fixer#3871) so I've introduced separate config for Travis to run.
I've also added `composer fix-cs` …
=> [CS] Configured PHP CS Fixer for Spec tests

src/API/QueryFieldService.php
| **JIRA issue**                          | [EZP-31675](https://jira.ez.no/browse/EZP-31675)
| **Target eZ Platform version** | `v2.x`, `v3.x`
Due to a `string` typehint in the Query Field Service, integer or boolean parameters always ended up as strings, causing errors in the Query Types options resolution.
=> EZP-31675: do not cast parameters part to string

src/eZ/ContentView/QueryResultsInjector.php
| **JIRA issue**                          | [EZP-31678](https://jira.ez.no/browse/EZP-31678)
| **Target eZ Platform version** | `v2.5`, `v3.0`, `v3.1`
The documented `itemViewType` field template parameter is now passed on to the inner view so that items rendering can be customized as expected.
=> Pass the itemViewType parameter to the inner view template

spec/API/QueryFieldServiceSpec.php, src/API/QueryFieldService.php
| **JIRA issue**                          | [EZP-31676](https://jira.ez.no/browse/EZP-31676)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v2.5`, `v3.0`, `v3.1`
| **BC breaks**                          | maybe...
| **Doc needed**                       | yes
Handles any predefined offset in the query (through parameters or through the query type itself).
The predefined offset is added to the one used for pagination, and removed from the total count.
=> EZP-31676: keep the offset defined in the query

composer.json
Failing build: https://travis-ci.com/ezsystems/ezplatform-query-fieldtype/builds/171629039
Admin-ui has a dependency on ezplatform-search which is not available in a stable version and needs to be added explicitly.
=> [Composer] Added ezplatform-search dependency to require-dev

spec/eZ/ContentView/FieldDefinitionIdentifierMatcherSpec.php, spec/eZ/ContentView/QueryResultsInjectorSpec.php, src/eZ/ContentView/FieldDefinitionIdentifierMatcher.php, src/eZ/ContentView/QueryResultsInjector.php
| **JIRA issue**                          | [EZP-31677](https://jira.ez.no/browse/EZP-31677)
| **Target eZ Platform version** | `v2.5`, `v3.0`, `v3.1`
| **Doc needed**                       | yes
Changes `FieldDefinitionIdentifier` matcher to actually test that the matched view is for the configured field definition identifier. To make it possible, the view must include a `fieldIdentifier` parameter set to the field being rendered.
=> Make FieldDefinitionIdentifier matcher actually test the field identifier

composer.json, spec/API/ExceptionSafeQueryFieldServiceSpec.php, src/API/ExceptionSafeQueryFieldService.php, src/Symfony/DependencyInjection/EzSystemsEzPlatformQueryFieldTypeExtension.php, src/Symfony/Resources/config/prod/services.yaml
| **JIRA issue**                          | [EZP-31707](https://jira.ez.no/browse/EZP-31707)
| **Target eZ Platform version** | `v3.1`
> Steps to reproduce:
> Create a content type with an `ezcontentquery` field. Select query type: `relatedTocontent`.
> Fill the parameters filed with :
> ```
> content: '@=content'
> field: 'test'
> ```
> Submit your content type.
> Create a new object for this content type.
This PR prevents pages with invalid `ezcontentquery` content from crashing. On production environments pages will receive empty …
=> EZP-31825: Fixed crashes when ezcontentquery field parameters are invalid

spec/API/QueryFieldServiceSpec.php, src/API/QueryFieldLocationService.php, src/API/QueryFieldService.php, src/API/QueryFieldServiceInterface.php, src/Controller/QueryFieldRestController.php, src/Symfony/Resources/config/services/services.yaml, src/Symfony/Resources/views/fieldtype/field_view.html.twig, src/eZ/ContentView/QueryResultsInjector.php, src/eZ/ContentView/QueryResultsWithLocationPagerFantaAdapter.php
| **JIRA issue**                          | [EZP-31659](https://jira.ez.no/browse/EZP-31659)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v2.x`, `v3.x`
| **Tests pass**                          | yes/no
| **Doc needed**                       | yes
Introduces a new `QueryFieldLocationService` that allow to get results / results slices / count results based on a location. With the previous methods, only `mainLocation` was available as a variable, since it was inferred from the content.
Now both can be available, and `location` will be set to the "current" location. In the context …
=> Support for getting the results for a location

src/API/ExceptionSafeQueryFieldService.php
| **JIRA issue**                          | [EZP-32325](https://issues.ibexa.co/browse/EZP-32325)
| **Target eZ Platform version** | Package: v2.3.1, product: v3.3.1
The `ExceptionSafeQueryFieldService`, used in `prod` env to make exceptions non blockers, wasn't updated to reflect the new interfaces.
=> EZP-32325: Made ExceptionSafeQueryFieldService implement QueryFieldLocationService

src/API/QueryFieldService.php
| **JIRA issue**                          | [EZP-32326](https://issues.ibexa.co/browse/EZP-32326)
| **Target eZ Platform version** | Package: v2.3.1, product: v3.3.1
Any offset defined in the query type must be kept when computing offset for pagination. It was the case before, but the lines got lost when the location pull-request was merged.
=> EZP-32326: Re-introduced query type offset
